### ISSUE TITLE
Allow using EightBaseAppProvider without auth

### ISSUE THREAD

**Issue by andrei-anisimov** [8base/sdk#134]
**Describe the bug**
It is impossible to run EightBaseAppProvider in unauthenticated mode without passing `authClient`

**To Reproduce**
Initialize `EightBaseAppClient` without passing `authClient`

**Expected behavior**
It should be possible to run EightBaseAppProvider without passing the `authClient`. This is useful for cases where authentication is not required.

**Comment by andrei-anisimov** [comment]
@zouxuoz is this done?

**Comment by zouxuoz** [comment]
@andrei-anisimov no, we can't do it fast now

**Comment by zouxuoz** [comment]
Implemented.
