### ISSUE TITLE
Ability to use EightBaseProvide with API token

### ISSUE THREAD

**Issue by andrei-anisimov** [8base/sdk#135]
**Is your feature request related to a problem? Please describe.**
We should add the ability to use EightBaseAppProvider with an API token instead of Auth0

**Describe the solution you'd like**
In a similar fashion as `Auth0WebAuthClient` we can create `APITokenClient` that will allow to authenticate via a token.

**Comment by zouxuoz** [comment]
Implemented

**Comment by zouxuoz** [comment]
Implemented
